# TCL File Generated by Component Editor 24.1
# Wed Dec 17 16:56:46 EST 2025
# DO NOT MODIFY


# 
# ads_seven_segment "ads_seven_segment" v1.0
#  2025.12.17.16:56:46
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ads_seven_segment
# 
set_module_property DESCRIPTION ""
set_module_property NAME ads_seven_segment
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ads_seven_segment
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sevenseg_core
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sevenseg_core.vhd VHDL PATH ../project-4-ads/sevenseg_core.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter lamp_mode_common_anode BOOLEAN true
set_parameter_property lamp_mode_common_anode DEFAULT_VALUE true
set_parameter_property lamp_mode_common_anode DISPLAY_NAME lamp_mode_common_anode
set_parameter_property lamp_mode_common_anode TYPE BOOLEAN
set_parameter_property lamp_mode_common_anode UNITS None
set_parameter_property lamp_mode_common_anode HDL_PARAMETER true
add_parameter decimal_support BOOLEAN true
set_parameter_property decimal_support DEFAULT_VALUE true
set_parameter_property decimal_support DISPLAY_NAME decimal_support
set_parameter_property decimal_support TYPE BOOLEAN
set_parameter_property decimal_support UNITS None
set_parameter_property decimal_support HDL_PARAMETER true
add_parameter implementer NATURAL 42 ""
set_parameter_property implementer DEFAULT_VALUE 42
set_parameter_property implementer DISPLAY_NAME implementer
set_parameter_property implementer WIDTH ""
set_parameter_property implementer TYPE NATURAL
set_parameter_property implementer ENABLED false
set_parameter_property implementer UNITS None
set_parameter_property implementer ALLOWED_RANGES 0:2147483647
set_parameter_property implementer DESCRIPTION ""
set_parameter_property implementer HDL_PARAMETER true
add_parameter revision NATURAL 1
set_parameter_property revision DEFAULT_VALUE 1
set_parameter_property revision DISPLAY_NAME revision
set_parameter_property revision TYPE NATURAL
set_parameter_property revision ENABLED false
set_parameter_property revision UNITS None
set_parameter_property revision HDL_PARAMETER true
add_parameter num_digits POSITIVE 6
set_parameter_property num_digits DEFAULT_VALUE 6
set_parameter_property num_digits DISPLAY_NAME num_digits
set_parameter_property num_digits TYPE POSITIVE
set_parameter_property num_digits UNITS None
set_parameter_property num_digits HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point digits
# 
add_interface digits conduit end
set_interface_property digits associatedClock clock
set_interface_property digits associatedReset ""
set_interface_property digits ENABLED true
set_interface_property digits EXPORT_OF ""
set_interface_property digits PORT_NAME_MAP ""
set_interface_property digits CMSIS_SVD_VARIABLES ""
set_interface_property digits SVD_ADDRESS_GROUP ""

add_interface_port digits lamps writeresponsevalid_n Output "(((num_digits*7)-1)) - (0) + 1"


# 
# connection point avalon_mm_agent
# 
add_interface avalon_mm_agent avalon end
set_interface_property avalon_mm_agent addressUnits WORDS
set_interface_property avalon_mm_agent associatedClock clock
set_interface_property avalon_mm_agent associatedReset reset
set_interface_property avalon_mm_agent bitsPerSymbol 8
set_interface_property avalon_mm_agent burstOnBurstBoundariesOnly false
set_interface_property avalon_mm_agent burstcountUnits WORDS
set_interface_property avalon_mm_agent explicitAddressSpan 0
set_interface_property avalon_mm_agent holdTime 0
set_interface_property avalon_mm_agent linewrapBursts false
set_interface_property avalon_mm_agent maximumPendingReadTransactions 0
set_interface_property avalon_mm_agent maximumPendingWriteTransactions 0
set_interface_property avalon_mm_agent readLatency 0
set_interface_property avalon_mm_agent readWaitTime 1
set_interface_property avalon_mm_agent setupTime 0
set_interface_property avalon_mm_agent timingUnits Cycles
set_interface_property avalon_mm_agent writeWaitTime 0
set_interface_property avalon_mm_agent ENABLED true
set_interface_property avalon_mm_agent EXPORT_OF ""
set_interface_property avalon_mm_agent PORT_NAME_MAP ""
set_interface_property avalon_mm_agent CMSIS_SVD_VARIABLES ""
set_interface_property avalon_mm_agent SVD_ADDRESS_GROUP ""

add_interface_port avalon_mm_agent address address Input 2
add_interface_port avalon_mm_agent read read Input 1
add_interface_port avalon_mm_agent readdata readdata Output 32
add_interface_port avalon_mm_agent write write Input 1
add_interface_port avalon_mm_agent writedata writedata Input 32
set_interface_assignment avalon_mm_agent embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_mm_agent embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_mm_agent embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_mm_agent embeddedsw.configuration.isPrintableDevice 0

